### ISSUE TITLE
Indicating which column is failing in DataFrameMapper

### ISSUE THREAD

**Issue by esquire900** [pandas-dev/sklearn-pandas#110]
Currently, when the DataFrameMapper fails, a generic error is shown that contains very little info about the place / column of the DataFrame where the error occurs, i.e.

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)`

With further debugging information that shows the DataFrameMapper code that fails, but provides no actual useful info for the end-user. I think that simply adding the name of the column that is failing in the error message (i.e. failed to apply method X to column Y) can be massive help in debugging :)

**Comment by arnau126** [comment]
I also think that it would be very useful!

However, looking at the code, I think that it won't be an easy task.
Give me some days to think about it. Any help or suggestion is welcomed.

**Comment by dukebody** [comment]
Arnau, I think it can be done by catching the exception and re raising it
with the columns names injected in the message.

Other possibilities are:
- catch it and raise another TransformationException. But this might break
code listening to concrete exceptions.
- logger.error the columns and raise the original exception. Problem here
is that loggers are probably not configured correctly in a notebook, and
moreover this can lead to duplicate error logging in many envs.

My preference is the injection keeping the exception type.

El dia 12 jul. 2017 13:31, "Arnau" <notifications@github.com> va escriure:

**Comment by dukebody** [comment]
@esquire900, @arnau126 I coded up a proposal for this feature, with a context manager stolen from StackOverflow :) let me know if it looks good to you. I also think that this small feature can be hugely useful for those using sklearn-pandas in a day-to-day basis!

**Comment by esquire900** [comment]
@dukebody this is (at least for me, but hopefully for others) hugely helpful. Thanks so much for coding this!

**Comment by dukebody** [comment]
@esquire900 @arnau126  please grab last master version and try it out! :)
