### ISSUE TITLE
sklearn-pandas don't support transfomer which will drop rows

### ISSUE THREAD

**Issue by scotthuang1989** [pandas-dev/sklearn-pandas#116]
In my pre-processing steps, I have to drop some rows with outliers. I try to do that with a custom transformer, and get this error:

ValueError: all the input array dimensions except for the concatenation axis must match exactly

I check the code, here is what I find:
1. this a behavior by implementation.
2. sklearn-pandas will process transformer one by one in the order defined by pass in list of transformers.
3. the data source for every transformer is the ***original data***, not the data from last transformer.
4. the processed data is added into a list. at the end of processing, all the processed columns will be concatenated.

my question is there other way of supporting drop-row operation with sklearn-pandas? I want to make sure there is no native support for this feature before I start coding my own.

**Comment by dukebody** [comment]
Hi @scotthuang1989. Can you post an excerpt of the code you are using to do the transformation? I suspect you are doing something wrong, because if you do:

```
DataFrameMapper([
    ('col1', [Tranformer1(), Tranformer2()])
])
```

the `Transformer2()` will applied to the result of applying `Transformer1()` to the `col1` of the dataframe. If you are not seeing this behaviour, like you suggest in point 3, it is clearly a bug and we should fix it.

**Comment by scotthuang1989** [comment]
Hi dukebody, 

I do following actions:

my data is dataframe with 2 columns: col1, col2
Here is my mapper:
DataFrameMapper([
    (['col1','col2'], Tranformer1()),
    ('col2', Tranformer2())
])

Transformer1() will drop some outlier by value of 'col1'，TransFormer2 will standardize  col2. 
Here is what I expect:
1. some of rows of this dataframe will be dropped.
2. Transformer2 will standardize col2 of remaining rows.

After read the source code. I think this is not a issue, the design of this lib is processing data by columns(as I posted in my original message). I wrote a new lib will process input dataframe as whole in each steps than pass the processed data to next steps( Transformer1 will process dataframe, then pass the processed dataframe to Transformer2, etc).  Can you kindly share the idea behind this design? I am new to ML, I am not sure if my way of doing this is in the right direction.

**Comment by arnau126** [comment]
> After read the source code. I think this is not a issue, the design of this lib is processing data by columns(as I posted in my original message)

Correct.

You might take a look at sklearn's `Pipeline`.
http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html

Using this objects you code would look like:
```
mapper1 = DataFrameMapper([
    (['col1','col2'], Tranformer1()),
])

mapper2 = DataFrameMapper([
    ('col2', Tranformer2()),
])

pipe = Pipeline([('mapper1', mapper1), ('mapper2', mapper2)])

df_transformed = pipe.transform(df)
```

I think that you will get what you want

> process input dataframe as whole in each steps than pass the processed data to next steps

**Comment by scotthuang1989** [comment]
@dukebody 
sorry for the "very late" response, I get hold up with some  other forget to check github.

for your question, I write a small sample code:

```
data = pd.DataFrame({'pet':      ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'],
                      'children': [4., 6, 3, 3, 2, 3, 5, 4],
                      'salary':   [90, 24, 44, 27, 32, 59, 36, 27]})

def DropLarge(X):
    return X[X<4]

DropLargeTransformer = FunctionTransformer(DropLarge)

test_mapper = DataFrameMapper([
   ("children",DropLargeTransformer),
    ("pet",sklearn.preprocessing.LabelBinarizer())
])

test_mapper.fit_transform(data)
```

ERROR message is:

> ValueError: all the input array dimensions except for the concatenation axis must match exactly

like I said, the way sklearn-pandas take is process all mapper, then combine the result together. So I don't think this is a issue, because to work around this, you guys need re-implements process functions.

@arnau126  like you said, What I want can be done with native functionality of scikit-learn.
