### ISSUE TITLE
inverse_transform() function?

### ISSUE THREAD

**Issue by franciscogmm** [pandas-dev/sklearn-pandas#118]
Hi all! just wanted to ask if it's possible to do an inverse transform function using DataFrameMapper? 

I realize that the class itself does not have a function like that, but has anyone else tried doing stuff manually? Any help would be great! or even save individual classes from labelencoders?

Thanks!

**Comment by dukebody** [comment]
This has already been discussed, goto https://github.com/pandas-dev/sklearn-pandas/issues/41. See the last comments there, perhaps you can help finishing the work?

Closing this one, please continue discussion in the other open ticket.
