### ISSUE TITLE
There seems to be some redundant code in DataFrameMapper._get_col_subset

### ISSUE THREAD

**Issue by HereticSK** [pandas-dev/sklearn-pandas#121]
1. in the definition of `DataFrameMapper._get_col_subset`, there are a few lines of code which ckecks whether X is a list
```Python
        if isinstance(X, list):
            X = [x[cols] for x in X]
            X = pd.DataFrame(X)
```
When would X be a list? If I understand the code correctly, `DataFrameMapper._get_col_subset` is called internally within  `DataFrameMapper.fit` and `DataFrameMapper.transform`. It receives its argument  `X` directly from the outer method, where `X` should passed as a pandas DataFrame or a numpy array. So is there any cases when `isinstance(X, list)` is `True`? Is there anything I am missing?

2. It seems that the  `return t` at the last line is redundant, as either `return t` or `return t.valuse` will be executed in the preceding block.
 ```Python
        if input_df:
            return t
        else:
            return t.values
        return t
 ```

I believe the redundancy mentioned above won't cause any trouble, but it can be kind of confusing for people to read to code.

I am new to sklean_pandas. Correct me if I am wrong. Thanks.

**Comment by dukebody** [comment]
Hi @HereticSK !

Thank you very much for taking the time to write such a detailed ticket.

1) You are right it seems redundant. IIRC this was something needed when dealing with quite old sklearn versions that weren't capable of dealing with pandas dataframes correctly. I'm removing that block and commiting the code if there are no feature tests failing. We don't aim to keep compatibility with old sklearn versions forever. :)

2) Absolutely right, this is probably some leftover code.

**Comment by dukebody** [comment]
Ok for (1) it seems that code block is needed for the cross-validation compatibility layers for sklearn>=0.16.0. We can drop that code block in sklearn-pandas 2.0 as advertised.

I will add a comment to the code to remember this. :)
