### ISSUE TITLE
transformed_names_ are not being unpickled.

### ISSUE THREAD

**Issue by trahflow** [pandas-dev/sklearn-pandas#127]
Hi,

the `DataFrameMapper.transformed_names_` are a convenient feature if one wants to inspect e.g. feature importances.
Unfortunately, right now this attribute is not being unpickled, as it is missing in `DataFrameMapper.__setstate__()`.
Adding it there should fix the issue.

**Comment by dukebody** [comment]
Thanks for the report! The cited commit should fix this.
