### ISSUE TITLE
PyPI version out-of-date and mislabelled as v1.3.0 

### ISSUE THREAD

**Issue by mdlynch37** [pandas-dev/sklearn-pandas#93]
Not sure if this issue belongs here, but....

Version that installs through pip command is listed as 1.3.0, different from current of GitHub 1.1.0
https://pypi.python.org/pypi/sklearn-pandas

Also, that PyPI version is missing the ```input_df``` argument, so I'm guessing it needs to be updated.

**Comment by dukebody** [comment]
Hi @mdlynch37 ! We have just released sklearn-pandas 1.4.0 to PYPI: https://pypi.python.org/pypi/sklearn-pandas

Can you check if this solves your issues?

**Comment by dukebody** [comment]
Closing due to lack of follow-up. Please reopen if the issue still persists.
