### ISSUE TITLE
Add to documentation: Preserve Index of Input DataFrame

### ISSUE THREAD

**Issue by dreyco676** [pandas-dev/sklearn-pandas#95]
For my workflow I need to retain the index for joining data back. It looks like this can be done as long as your index is the same numeric type as the rest of the columns you are transforming.

Create the index as a column and set the type
`df['index'] = df.index.astype('int64')`

Create the mapper with no transformations to the 'index' column
`mapper = DataFrameMapper([('text_col', CountVectorizer()), ('index', None)], df_out=True)`
`transformed_df = mapper.fit_transform(df.copy())`

Set the index using the 'index' column again
`transformed_df = transformed_df.set_index('index')`

**Comment by dukebody** [comment]
Hmm, it would be much better if `sklearn-pandas` preserved the index automatically when using `df_out=True`, right? Shouldn't be very hard to do. Would you be willing to create a PR implementing this feature?
