### ISSUE TITLE
how can I use a generated feature in another feature

### ISSUE THREAD

**Issue by ragrawal** [pandas-dev/sklearn-pandas#97]
Hi,

Is there a way to use a derived feature in another transformer. For instance I need something like this

DataFrameMapper([
    ('start_timestamp', toDateStringTransformer(), {'alias': 'datestr'}),
    (['field1', 'datestr'], FeatureGenerator(), {'input_df': True}),
])

Above I am first converting a start_timestamp to detester and then generating some additional features based on field1 and detester.

**Comment by dukebody** [comment]
Right now this is not possible with one `DataFrameMapper`, and I think it would make the whole thing much more complex.

What you can probably do is chain two `DataFrameMapper`s. Something like:

```
mapper_1 = DataFrameMapper([
('start_timestamp', toDateStringTransformer(), {'alias': 'datestr'}),
], default=None, df_out=True)

mapper_2 = DataFrameMapper([
(['field1', 'datestr'], FeatureGenerator(), {'input_df': True}),
])

result = mapper_2.fit_transform(mapper_1.fit_transform(X))
```

Does this make sense?

**Comment by ragrawal** [comment]
Yup. that make sense.
